### ISSUE TITLE
<type 'exceptions.OSError'>: out of pty devices

### ISSUE THREAD

**Issue by AymaneZizi** [media-centre/makenews#142]
hello,
Thanks for writing such great app.
i am trying to import the repository into bitbucket but i keep getting this error :
```
Remote Git clone failed: <type 'exceptions.OSError'>: out of pty devices
```
how can i solve it ?

**Comment by muralikrishna8** [comment]
Hi,

Could you please share the command that you are running and system configuration.

**Comment by AymaneZizi** [comment]
Hello Murali,
i logged into bitbucket, tried to import repository there, so i got this error. 
you can try it out by yourself.
regards,
