### ISSUE TITLE
Issue while running oneClickInstaller.sh

### ISSUE THREAD

**Issue by akhiha** [media-centre/makenews#146]
Hello,
I am finding error while i am running oneClickInstaller.sh. Its necessary for to deploy tis in my system. So, i would be glad if i get help regarding this.
The errors which i am gettinbg are as follows:

--- creating couchdb admin username and password
{"error":"unauthorized","reason":"You are not a server admin."}
--- creation of admin account completed. May be success or failed
--- creating common db
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
--- creation of common db completed. May be success or failed
--- creating _users DB
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
--- creating _users db is completed. may be success of failed.
--- creating _replicator
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
--- creating _replicator db is completed. may be success of failed.
--- creating _global_changes
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
--- creating _global_changes db is completed. may be success of failed.
"true"
"http://127.0.0.1:5000"
"true"
"GET, PUT, POST, HEAD, DELETE"
"accept, authorization, content-type, origin, referer, x-csrf-token"
npm WARN react-redux@2.1.2 requires a peer of redux@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

audited 16653 packages in 13.058s
found 4 vulnerabilities (2 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
/home/sapna/makenews/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /home/sapna/makenews/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/sapna/makenews/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/sapna/makenews/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sapna/makenews/node_modules/gulp-sass/index.js:162:21)
/home/sapna/makenews/dist/server/src/migration.js:2
import Migration from "./migration/Migration";
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Enter user name to be created
akhila
Enter password for the user akhila
Re-enter password for the user akhila
/home/sapna/makenews/dist/server/src/createUser.js:2
import AdminDbClient from "./db/AdminDbClient";
       ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Thanks in Advance.

**Comment by diangarkov** [comment]
I have the same issue, does someone know, how we could fix it?

**Comment by diangarkov** [comment]
I fixed the same problems and I would like to say where exactly the problem is.

First of all, you should have preinstalled npm, couchdb and couchdb lucene.
1)Check that  you created an admin use in couchdb with whom you can create, delete and change databases manually on the localhost:5984/_utils/# 
If you admin user in couchdb is not with the name 'admin' and password 'admin', change it in the file instal.config from this very project.
2) check that you have configurate correctly the couchdb-lucene. This was the main problem for these errors.
3) If you have not installed gulp - install it also.
4) after running the server see both consoles - the console of the browser and the cmd prompt for some errors
4.1) In some cases, it is necessary  to go to 127.0.0.1:5000 instead of localhost:5000, because of CORS, if you want to log in.
4.2) In some other, after trying to login the process in the cmd prompt crashes because of the permissions. That^s why you should start the server with sudo(just 'sudo node dist/server').

The website should work properly after these steps but if you have some problems to install couchdb or to connect it to couchdb-lucene, just to know that if you have or use  mac os - the installation is very faster and there is almost no configurations between couchdb and couchdb-lucene.

**Comment by diangarkov** [comment]
@muralikrishna8 
do you think that the issue could be closed already?

**Comment by muralikrishna8** [comment]
@diangarkov,

I think your solution would solve the problem.

But I think we need to update the ReadMe to make it more clear or fix the oneClickInstaller for better error reporting

**Comment by diangarkov** [comment]
yes, I will update the readme file, thanks also.

**Comment by diangarkov** [comment]
can you assign this issue to me? I am fixing it on our fork that we would want to merge to this master.

**Comment by akhiha** [comment]
> Hello,
> I am finding error while i am running oneClickInstaller.sh. Its necessary for to deploy tis in my system. So, i would be glad if i get help regarding this.
> The errors which i am gettinbg are as follows:
> 
> --- creating couchdb admin username and password
> {"error":"unauthorized","reason":"You are not a server admin."}
> --- creation of admin account completed. May be success or failed
> --- creating common db
> {"error":"file_exists","reason":"The database could not be created, the file already exists."}
> --- creation of common db completed. May be success or failed
> --- creating _users DB
> {"error":"file_exists","reason":"The database could not be created, the file already exists."}
> --- creating _users db is completed. may be success of failed.
> --- creating _replicator
> {"error":"file_exists","reason":"The database could not be created, the file already exists."}
> --- creating _replicator db is completed. may be success of failed.
> --- creating _global_changes
> {"error":"file_exists","reason":"The database could not be created, the file already exists."}
> --- creating _global_changes db is completed. may be success of failed.
> "true"
> "http://127.0.0.1:5000"
> "true"
> "GET, PUT, POST, HEAD, DELETE"
> "accept, authorization, content-type, origin, referer, x-csrf-token"
> npm WARN react-redux@2.1.2 requires a peer of redux@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
> 
> audited 16653 packages in 13.058s
> found 4 vulnerabilities (2 low, 1 moderate, 1 high)
> run `npm audit fix` to fix them, or `npm audit` for details
> /home/sapna/makenews/node_modules/node-sass/lib/binding.js:15
> throw new Error(errors.missingBinary());
> ^
> 
> Error: Missing binding /home/sapna/makenews/node_modules/node-sass/vendor/linux-x64-57/binding.node
> Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
> 
> Found bindings for the following environments:
> 
>     * Linux 64-bit with Node.js 10.x
> 
> 
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass` to download the binding for your current environment.
> at module.exports (/home/sapna/makenews/node_modules/node-sass/lib/binding.js:15:13)
> at Object. (/home/sapna/makenews/node_modules/node-sass/lib/index.js:14:35)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object. (/home/sapna/makenews/node_modules/gulp-sass/index.js:162:21)
> /home/sapna/makenews/dist/server/src/migration.js:2
> import Migration from "./migration/Migration";
> ^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
> at Module._compile (internal/modules/cjs/loader.js:723:23)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> at startup (internal/bootstrap/node.js:283:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> Enter user name to be created
> akhila
> Enter password for the user akhila
> Re-enter password for the user akhila
> /home/sapna/makenews/dist/server/src/createUser.js:2
> import AdminDbClient from "./db/AdminDbClient";
> ^^^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
> at Module._compile (internal/modules/cjs/loader.js:723:23)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> at startup (internal/bootstrap/node.js:283:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> 
>

I have cleared this issue. Thanks
